general:
  seed: 0

path:
  data_csv: /media/benamira/19793564030D4273/MCsBackup/Alexis_project/my_IMDB_guess/data/MovieGenre.csv
  data_posters: /media/benamira/19793564030D4273/MCsBackup/Alexis_project/movie_poster/
  data_path_train: /media/benamira/19793564030D4273/MCsBackup/Alexis_project/movie_poster/train
  data_path_val: /media/benamira/19793564030D4273/MCsBackup/Alexis_project/movie_poster/val
  data_path_test: /media/benamira/19793564030D4273/MCsBackup/Alexis_project/movie_poster/test
  result_path_model: ./mytraining.pt
  logs_tensorboard: ./runs/test_1

train:
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 2
  num_workers: 2
