general:
  seed: 0

path:
  data_csv: ./Alexis_project/my_IMDB_guess/data/MovieGenre.csv
  data_posters: ./Alexis_project/movie_poster/
  data_path_train: /content/my_little_dataset/train
  data_path_val: /content/my_little_dataset/val
  data_path_test: /content/my_little_dataset/test
  result_path_model: /content/mytraining.pt
  logs_tensorboard: ./runs/test_1
